{{- if .Values.route.enabled -}}
{{- $fullName := include "starter-kit.fullname" . -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ $fullName }}  
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
    haproxy.router.openshift.io/appid-auth: bindSecret=binding-sandbox-ocp431-one-appid namespace=dev5-yks requestType=web serviceName=inv-ui-appid-yks idToken=true
spec:
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
  tls:
    termination: edge
  wildcardPolicy: None
{{- end }}